// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mail.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMailInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 204423755;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mail_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AccountDto> crateApiMailAddImapAccount({
    required String email,
    required String host,
    required int port,
    required String password,
    required String displayName,
  });

  Future<void> crateApiMailArchiveThread({required PlatformInt64 threadId});

  Future<DraftDto> crateApiMailForwardDraft({required PlatformInt64 threadId});

  Future<void> crateApiMailInitApp();

  Future<List<AccountDto>> crateApiMailListAccounts();

  Future<List<FolderDto>> crateApiMailListFolders({
    required PlatformInt64 accountId,
  });

  Future<List<ThreadDto>> crateApiMailListThreads({
    required String query,
    required int limit,
  });

  Future<void> crateApiMailMarkRead({
    required PlatformInt64 threadId,
    required bool read,
  });

  Future<DraftDto> crateApiMailNewDraft({PlatformInt64? accountId});

  Future<void> crateApiMailOpenCore({required String dataDir});

  Future<void> crateApiMailRemoveAccount({required PlatformInt64 id});

  Future<DraftDto> crateApiMailReplyDraft({
    required PlatformInt64 threadId,
    required bool replyAll,
  });

  Future<void> crateApiMailSendDraft({required DraftDto draft});

  Future<void> crateApiMailStarThread({
    required PlatformInt64 threadId,
    required bool on_,
  });

  Future<SyncSummaryDto> crateApiMailSyncAll({required bool inboxOnly});

  Stream<SyncEventDto> crateApiMailSyncEvents();

  Future<void> crateApiMailTestImapLogin({
    required String email,
    required String host,
    required int port,
    required String password,
  });

  Future<List<MessageDto>> crateApiMailThreadMessages({
    required PlatformInt64 threadId,
  });

  Future<void> crateApiMailTrashThread({required PlatformInt64 threadId});

  Future<int> crateApiMailUnreadCount();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AccountDto> crateApiMailAddImapAccount({
    required String email,
    required String host,
    required int port,
    required String password,
    required String displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(password, serializer);
          sse_encode_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailAddImapAccountConstMeta,
        argValues: [email, host, port, password, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailAddImapAccountConstMeta => const TaskConstMeta(
    debugName: "add_imap_account",
    argNames: ["email", "host", "port", "password", "displayName"],
  );

  @override
  Future<void> crateApiMailArchiveThread({required PlatformInt64 threadId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailArchiveThreadConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailArchiveThreadConstMeta =>
      const TaskConstMeta(debugName: "archive_thread", argNames: ["threadId"]);

  @override
  Future<DraftDto> crateApiMailForwardDraft({required PlatformInt64 threadId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_draft_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailForwardDraftConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailForwardDraftConstMeta =>
      const TaskConstMeta(debugName: "forward_draft", argNames: ["threadId"]);

  @override
  Future<void> crateApiMailInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMailInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<AccountDto>> crateApiMailListAccounts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailListAccountsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailListAccountsConstMeta =>
      const TaskConstMeta(debugName: "list_accounts", argNames: []);

  @override
  Future<List<FolderDto>> crateApiMailListFolders({
    required PlatformInt64 accountId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(accountId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_folder_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailListFoldersConstMeta,
        argValues: [accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailListFoldersConstMeta =>
      const TaskConstMeta(debugName: "list_folders", argNames: ["accountId"]);

  @override
  Future<List<ThreadDto>> crateApiMailListThreads({
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_thread_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailListThreadsConstMeta,
        argValues: [query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailListThreadsConstMeta => const TaskConstMeta(
    debugName: "list_threads",
    argNames: ["query", "limit"],
  );

  @override
  Future<void> crateApiMailMarkRead({
    required PlatformInt64 threadId,
    required bool read,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          sse_encode_bool(read, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailMarkReadConstMeta,
        argValues: [threadId, read],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailMarkReadConstMeta => const TaskConstMeta(
    debugName: "mark_read",
    argNames: ["threadId", "read"],
  );

  @override
  Future<DraftDto> crateApiMailNewDraft({PlatformInt64? accountId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_i_64(accountId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_draft_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailNewDraftConstMeta,
        argValues: [accountId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailNewDraftConstMeta =>
      const TaskConstMeta(debugName: "new_draft", argNames: ["accountId"]);

  @override
  Future<void> crateApiMailOpenCore({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailOpenCoreConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailOpenCoreConstMeta =>
      const TaskConstMeta(debugName: "open_core", argNames: ["dataDir"]);

  @override
  Future<void> crateApiMailRemoveAccount({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailRemoveAccountConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailRemoveAccountConstMeta =>
      const TaskConstMeta(debugName: "remove_account", argNames: ["id"]);

  @override
  Future<DraftDto> crateApiMailReplyDraft({
    required PlatformInt64 threadId,
    required bool replyAll,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          sse_encode_bool(replyAll, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_draft_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailReplyDraftConstMeta,
        argValues: [threadId, replyAll],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailReplyDraftConstMeta => const TaskConstMeta(
    debugName: "reply_draft",
    argNames: ["threadId", "replyAll"],
  );

  @override
  Future<void> crateApiMailSendDraft({required DraftDto draft}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_draft_dto(draft, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailSendDraftConstMeta,
        argValues: [draft],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailSendDraftConstMeta =>
      const TaskConstMeta(debugName: "send_draft", argNames: ["draft"]);

  @override
  Future<void> crateApiMailStarThread({
    required PlatformInt64 threadId,
    required bool on_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailStarThreadConstMeta,
        argValues: [threadId, on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailStarThreadConstMeta => const TaskConstMeta(
    debugName: "star_thread",
    argNames: ["threadId", "on_"],
  );

  @override
  Future<SyncSummaryDto> crateApiMailSyncAll({required bool inboxOnly}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(inboxOnly, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_summary_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailSyncAllConstMeta,
        argValues: [inboxOnly],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailSyncAllConstMeta =>
      const TaskConstMeta(debugName: "sync_all", argNames: ["inboxOnly"]);

  @override
  Stream<SyncEventDto> crateApiMailSyncEvents() {
    final sink = RustStreamSink<SyncEventDto>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sync_event_dto_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMailSyncEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMailSyncEventsConstMeta =>
      const TaskConstMeta(debugName: "sync_events", argNames: ["sink"]);

  @override
  Future<void> crateApiMailTestImapLogin({
    required String email,
    required String host,
    required int port,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(email, serializer);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailTestImapLoginConstMeta,
        argValues: [email, host, port, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailTestImapLoginConstMeta => const TaskConstMeta(
    debugName: "test_imap_login",
    argNames: ["email", "host", "port", "password"],
  );

  @override
  Future<List<MessageDto>> crateApiMailThreadMessages({
    required PlatformInt64 threadId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_message_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailThreadMessagesConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailThreadMessagesConstMeta =>
      const TaskConstMeta(debugName: "thread_messages", argNames: ["threadId"]);

  @override
  Future<void> crateApiMailTrashThread({required PlatformInt64 threadId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(threadId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailTrashThreadConstMeta,
        argValues: [threadId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailTrashThreadConstMeta =>
      const TaskConstMeta(debugName: "trash_thread", argNames: ["threadId"]);

  @override
  Future<int> crateApiMailUnreadCount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMailUnreadCountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMailUnreadCountConstMeta =>
      const TaskConstMeta(debugName: "unread_count", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SyncEventDto> dco_decode_StreamSink_sync_event_dto_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountDto dco_decode_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AccountDto(
      id: dco_decode_i_64(arr[0]),
      email: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      displayName: dco_decode_String(arr[3]),
      unread: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DraftDto dco_decode_box_autoadd_draft_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_draft_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  DraftDto dco_decode_draft_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DraftDto(
      accountId: dco_decode_i_64(arr[0]),
      from: dco_decode_String(arr[1]),
      to: dco_decode_list_String(arr[2]),
      cc: dco_decode_list_String(arr[3]),
      bcc: dco_decode_list_String(arr[4]),
      subject: dco_decode_String(arr[5]),
      text: dco_decode_String(arr[6]),
      inReplyTo: dco_decode_opt_String(arr[7]),
      references: dco_decode_list_String(arr[8]),
    );
  }

  @protected
  FolderDto dco_decode_folder_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FolderDto(
      id: dco_decode_i_64(arr[0]),
      accountId: dco_decode_i_64(arr[1]),
      name: dco_decode_String(arr[2]),
      role: dco_decode_String(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AccountDto> dco_decode_list_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_account_dto).toList();
  }

  @protected
  List<FolderDto> dco_decode_list_folder_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_folder_dto).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ThreadDto> dco_decode_list_thread_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_thread_dto).toList();
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return MessageDto(
      id: dco_decode_i_64(arr[0]),
      threadId: dco_decode_i_64(arr[1]),
      fromName: dco_decode_String(arr[2]),
      fromAddr: dco_decode_String(arr[3]),
      to: dco_decode_list_String(arr[4]),
      date: dco_decode_i_64(arr[5]),
      snippet: dco_decode_String(arr[6]),
      text: dco_decode_opt_String(arr[7]),
      html: dco_decode_opt_String(arr[8]),
      blockedImages: dco_decode_u_32(arr[9]),
      hasAttachment: dco_decode_bool(arr[10]),
      unread: dco_decode_bool(arr[11]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SyncEventDto dco_decode_sync_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SyncEventDto(
      kind: dco_decode_String(arr[0]),
      accountId: dco_decode_i_64(arr[1]),
      folder: dco_decode_String(arr[2]),
      fetched: dco_decode_u_32(arr[3]),
      removed: dco_decode_u_32(arr[4]),
      message: dco_decode_String(arr[5]),
    );
  }

  @protected
  SyncSummaryDto dco_decode_sync_summary_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SyncSummaryDto(
      accounts: dco_decode_u_32(arr[0]),
      fetched: dco_decode_u_32(arr[1]),
      removed: dco_decode_u_32(arr[2]),
      errors: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  ThreadDto dco_decode_thread_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ThreadDto(
      id: dco_decode_i_64(arr[0]),
      accountId: dco_decode_i_64(arr[1]),
      subject: dco_decode_String(arr[2]),
      participants: dco_decode_list_String(arr[3]),
      lastDate: dco_decode_i_64(arr[4]),
      msgCount: dco_decode_u_32(arr[5]),
      unreadCount: dco_decode_u_32(arr[6]),
      snippet: dco_decode_String(arr[7]),
      hasAttachment: dco_decode_bool(arr[8]),
      starred: dco_decode_bool(arr[9]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SyncEventDto> sse_decode_StreamSink_sync_event_dto_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_unread = sse_decode_u_32(deserializer);
    return AccountDto(
      id: var_id,
      email: var_email,
      kind: var_kind,
      displayName: var_displayName,
      unread: var_unread,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DraftDto sse_decode_box_autoadd_draft_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_draft_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  DraftDto sse_decode_draft_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accountId = sse_decode_i_64(deserializer);
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_list_String(deserializer);
    var var_cc = sse_decode_list_String(deserializer);
    var var_bcc = sse_decode_list_String(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_inReplyTo = sse_decode_opt_String(deserializer);
    var var_references = sse_decode_list_String(deserializer);
    return DraftDto(
      accountId: var_accountId,
      from: var_from,
      to: var_to,
      cc: var_cc,
      bcc: var_bcc,
      subject: var_subject,
      text: var_text,
      inReplyTo: var_inReplyTo,
      references: var_references,
    );
  }

  @protected
  FolderDto sse_decode_folder_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_accountId = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    return FolderDto(
      id: var_id,
      accountId: var_accountId,
      name: var_name,
      role: var_role,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AccountDto> sse_decode_list_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AccountDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_account_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FolderDto> sse_decode_list_folder_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FolderDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_folder_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ThreadDto> sse_decode_list_thread_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ThreadDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_thread_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_threadId = sse_decode_i_64(deserializer);
    var var_fromName = sse_decode_String(deserializer);
    var var_fromAddr = sse_decode_String(deserializer);
    var var_to = sse_decode_list_String(deserializer);
    var var_date = sse_decode_i_64(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_html = sse_decode_opt_String(deserializer);
    var var_blockedImages = sse_decode_u_32(deserializer);
    var var_hasAttachment = sse_decode_bool(deserializer);
    var var_unread = sse_decode_bool(deserializer);
    return MessageDto(
      id: var_id,
      threadId: var_threadId,
      fromName: var_fromName,
      fromAddr: var_fromAddr,
      to: var_to,
      date: var_date,
      snippet: var_snippet,
      text: var_text,
      html: var_html,
      blockedImages: var_blockedImages,
      hasAttachment: var_hasAttachment,
      unread: var_unread,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SyncEventDto sse_decode_sync_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_accountId = sse_decode_i_64(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_fetched = sse_decode_u_32(deserializer);
    var var_removed = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return SyncEventDto(
      kind: var_kind,
      accountId: var_accountId,
      folder: var_folder,
      fetched: var_fetched,
      removed: var_removed,
      message: var_message,
    );
  }

  @protected
  SyncSummaryDto sse_decode_sync_summary_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accounts = sse_decode_u_32(deserializer);
    var var_fetched = sse_decode_u_32(deserializer);
    var var_removed = sse_decode_u_32(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    return SyncSummaryDto(
      accounts: var_accounts,
      fetched: var_fetched,
      removed: var_removed,
      errors: var_errors,
    );
  }

  @protected
  ThreadDto sse_decode_thread_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_accountId = sse_decode_i_64(deserializer);
    var var_subject = sse_decode_String(deserializer);
    var var_participants = sse_decode_list_String(deserializer);
    var var_lastDate = sse_decode_i_64(deserializer);
    var var_msgCount = sse_decode_u_32(deserializer);
    var var_unreadCount = sse_decode_u_32(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    var var_hasAttachment = sse_decode_bool(deserializer);
    var var_starred = sse_decode_bool(deserializer);
    return ThreadDto(
      id: var_id,
      accountId: var_accountId,
      subject: var_subject,
      participants: var_participants,
      lastDate: var_lastDate,
      msgCount: var_msgCount,
      unreadCount: var_unreadCount,
      snippet: var_snippet,
      hasAttachment: var_hasAttachment,
      starred: var_starred,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_sync_event_dto_Sse(
    RustStreamSink<SyncEventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_event_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_u_32(self.unread, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_draft_dto(
    DraftDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_draft_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_draft_dto(DraftDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.accountId, serializer);
    sse_encode_String(self.from, serializer);
    sse_encode_list_String(self.to, serializer);
    sse_encode_list_String(self.cc, serializer);
    sse_encode_list_String(self.bcc, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.inReplyTo, serializer);
    sse_encode_list_String(self.references, serializer);
  }

  @protected
  void sse_encode_folder_dto(FolderDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.accountId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.role, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_account_dto(
    List<AccountDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_account_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_folder_dto(
    List<FolderDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_folder_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_thread_dto(
    List<ThreadDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_thread_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.threadId, serializer);
    sse_encode_String(self.fromName, serializer);
    sse_encode_String(self.fromAddr, serializer);
    sse_encode_list_String(self.to, serializer);
    sse_encode_i_64(self.date, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.html, serializer);
    sse_encode_u_32(self.blockedImages, serializer);
    sse_encode_bool(self.hasAttachment, serializer);
    sse_encode_bool(self.unread, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_sync_event_dto(SyncEventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_i_64(self.accountId, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_u_32(self.fetched, serializer);
    sse_encode_u_32(self.removed, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_sync_summary_dto(
    SyncSummaryDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.accounts, serializer);
    sse_encode_u_32(self.fetched, serializer);
    sse_encode_u_32(self.removed, serializer);
    sse_encode_list_String(self.errors, serializer);
  }

  @protected
  void sse_encode_thread_dto(ThreadDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_i_64(self.accountId, serializer);
    sse_encode_String(self.subject, serializer);
    sse_encode_list_String(self.participants, serializer);
    sse_encode_i_64(self.lastDate, serializer);
    sse_encode_u_32(self.msgCount, serializer);
    sse_encode_u_32(self.unreadCount, serializer);
    sse_encode_String(self.snippet, serializer);
    sse_encode_bool(self.hasAttachment, serializer);
    sse_encode_bool(self.starred, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
