// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attachment_to_dto`, `core`, `draft_to_dto`, `dto_to_attachment`, `dto_to_draft`, `fmt_addr`, `new`, `parse_addr`

/// Open (or create) the profile database under `data_dir`. Idempotent.
Future<void> openCore({required String dataDir}) =>
    RustLib.instance.api.crateApiMailOpenCore(dataDir: dataDir);

Future<List<AccountDto>> listAccounts() =>
    RustLib.instance.api.crateApiMailListAccounts();

Future<AccountDto> addImapAccount({
  required String email,
  required String host,
  required int port,
  required String password,
  required String displayName,
}) => RustLib.instance.api.crateApiMailAddImapAccount(
  email: email,
  host: host,
  port: port,
  password: password,
  displayName: displayName,
);

/// Connect + authenticate once; nothing is stored. The error text carries the server's reason.
Future<void> testImapLogin({
  required String email,
  required String host,
  required int port,
  required String password,
}) => RustLib.instance.api.crateApiMailTestImapLogin(
  email: email,
  host: host,
  port: port,
  password: password,
);

Future<void> removeAccount({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMailRemoveAccount(id: id);

Future<List<FolderDto>> listFolders({required PlatformInt64 accountId}) =>
    RustLib.instance.api.crateApiMailListFolders(accountId: accountId);

Future<List<ThreadDto>> listThreads({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiMailListThreads(query: query, limit: limit);

Future<List<MessageDto>> threadMessages({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailThreadMessages(threadId: threadId);

/// Sanitized HTML body of one message. With `load_images`, remote images stay in and inline
/// images missing from the cache are fetched from the server.
Future<String?> messageHtml({
  required PlatformInt64 messageId,
  required bool loadImages,
}) => RustLib.instance.api.crateApiMailMessageHtml(
  messageId: messageId,
  loadImages: loadImages,
);

/// Path of the attachment in the app's file cache (fetched from the server when needed).
/// This is the file to hand to "open with" or a share sheet.
Future<String> openAttachment({
  required PlatformInt64 messageId,
  required int idx,
}) => RustLib.instance.api.crateApiMailOpenAttachment(
  messageId: messageId,
  idx: idx,
);

/// Save an attachment into `dir` under a free name; returns the path written.
Future<String> saveAttachment({
  required PlatformInt64 messageId,
  required int idx,
  required String dir,
}) => RustLib.instance.api.crateApiMailSaveAttachment(
  messageId: messageId,
  idx: idx,
  dir: dir,
);

/// Describe a local file for a draft: name, size, MIME type from the extension.
Future<DraftAttachmentDto> describeFile({required String path}) =>
    RustLib.instance.api.crateApiMailDescribeFile(path: path);

Future<int> unreadCount() => RustLib.instance.api.crateApiMailUnreadCount();

Future<void> archiveThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailArchiveThread(threadId: threadId);

Future<void> trashThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailTrashThread(threadId: threadId);

Future<void> markRead({required PlatformInt64 threadId, required bool read}) =>
    RustLib.instance.api.crateApiMailMarkRead(threadId: threadId, read: read);

Future<void> starThread({required PlatformInt64 threadId, required bool on_}) =>
    RustLib.instance.api.crateApiMailStarThread(threadId: threadId, on_: on_);

Future<DraftDto> replyDraft({
  required PlatformInt64 threadId,
  required bool replyAll,
}) => RustLib.instance.api.crateApiMailReplyDraft(
  threadId: threadId,
  replyAll: replyAll,
);

Future<DraftDto> forwardDraft({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailForwardDraft(threadId: threadId);

/// Empty draft from the given account (or the first one).
Future<DraftDto> newDraft({PlatformInt64? accountId}) =>
    RustLib.instance.api.crateApiMailNewDraft(accountId: accountId);

/// SMTP send; copies to Sent where the server does not; flags the original as answered.
Future<void> sendDraft({required DraftDto draft}) =>
    RustLib.instance.api.crateApiMailSendDraft(draft: draft);

Future<SyncSummaryDto> syncAll({required bool inboxOnly}) =>
    RustLib.instance.api.crateApiMailSyncAll(inboxOnly: inboxOnly);

/// Sit in IMAP IDLE on the account's inbox. Returns true when the server reported a change,
/// false when `timeout_secs` passed quietly. Errors surface as exceptions (no connection, auth…).
Future<bool> waitForChange({
  required PlatformInt64 accountId,
  required int timeoutSecs,
}) => RustLib.instance.api.crateApiMailWaitForChange(
  accountId: accountId,
  timeoutSecs: timeoutSecs,
);

/// Sync one account (inbox only when `inbox_only`).
Future<SyncSummaryDto> syncAccount({
  required PlatformInt64 accountId,
  required bool inboxOnly,
}) => RustLib.instance.api.crateApiMailSyncAccount(
  accountId: accountId,
  inboxOnly: inboxOnly,
);

/// Subscribe to sync events. The stream stays open for the life of the app.
Stream<SyncEventDto> syncEvents() =>
    RustLib.instance.api.crateApiMailSyncEvents();

class AccountDto {
  final PlatformInt64 id;
  final String email;
  final String kind;
  final String displayName;
  final int unread;

  const AccountDto({
    required this.id,
    required this.email,
    required this.kind,
    required this.displayName,
    required this.unread,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      email.hashCode ^
      kind.hashCode ^
      displayName.hashCode ^
      unread.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email &&
          kind == other.kind &&
          displayName == other.displayName &&
          unread == other.unread;
}

class AttachmentDto {
  final PlatformInt64 messageId;
  final int idx;
  final String name;
  final String mime;
  final PlatformInt64 size;

  const AttachmentDto({
    required this.messageId,
    required this.idx,
    required this.name,
    required this.mime,
    required this.size,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      idx.hashCode ^
      name.hashCode ^
      mime.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          idx == other.idx &&
          name == other.name &&
          mime == other.mime &&
          size == other.size;
}

/// A file going out with a draft: a local `path`, or part `idx` of stored message `message_id`.
class DraftAttachmentDto {
  final String name;
  final String mime;
  final PlatformInt64 size;
  final String? path;
  final PlatformInt64? messageId;
  final int? idx;

  const DraftAttachmentDto({
    required this.name,
    required this.mime,
    required this.size,
    this.path,
    this.messageId,
    this.idx,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mime.hashCode ^
      size.hashCode ^
      path.hashCode ^
      messageId.hashCode ^
      idx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftAttachmentDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mime == other.mime &&
          size == other.size &&
          path == other.path &&
          messageId == other.messageId &&
          idx == other.idx;
}

/// A message being written. Addresses are `Name <addr>` or bare `addr`.
class DraftDto {
  final PlatformInt64 accountId;
  final String from;
  final List<String> to;
  final List<String> cc;
  final List<String> bcc;
  final String subject;
  final String text;
  final String? inReplyTo;
  final List<String> references;
  final List<DraftAttachmentDto> attachments;

  const DraftDto({
    required this.accountId,
    required this.from,
    required this.to,
    required this.cc,
    required this.bcc,
    required this.subject,
    required this.text,
    this.inReplyTo,
    required this.references,
    required this.attachments,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      from.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      bcc.hashCode ^
      subject.hashCode ^
      text.hashCode ^
      inReplyTo.hashCode ^
      references.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          from == other.from &&
          to == other.to &&
          cc == other.cc &&
          bcc == other.bcc &&
          subject == other.subject &&
          text == other.text &&
          inReplyTo == other.inReplyTo &&
          references == other.references &&
          attachments == other.attachments;
}

class FolderDto {
  final PlatformInt64 id;
  final PlatformInt64 accountId;
  final String name;
  final String role;

  const FolderDto({
    required this.id,
    required this.accountId,
    required this.name,
    required this.role,
  });

  @override
  int get hashCode =>
      id.hashCode ^ accountId.hashCode ^ name.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          name == other.name &&
          role == other.role;
}

class MessageDto {
  final PlatformInt64 id;
  final PlatformInt64 threadId;
  final String fromName;
  final String fromAddr;
  final List<String> to;
  final PlatformInt64 date;
  final String snippet;

  /// Plain text body, derived from HTML when the message has no text part.
  final String? text;

  /// Sanitized HTML (no scripts, styles, forms; remote images blocked → `data-blocked-src`).
  final String? html;

  /// Remote images blocked plus inline images not available offline.
  final int blockedImages;
  final bool hasAttachment;
  final bool unread;

  /// Real attachments only; inline images render inside `html`.
  final List<AttachmentDto> attachments;

  const MessageDto({
    required this.id,
    required this.threadId,
    required this.fromName,
    required this.fromAddr,
    required this.to,
    required this.date,
    required this.snippet,
    this.text,
    this.html,
    required this.blockedImages,
    required this.hasAttachment,
    required this.unread,
    required this.attachments,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      threadId.hashCode ^
      fromName.hashCode ^
      fromAddr.hashCode ^
      to.hashCode ^
      date.hashCode ^
      snippet.hashCode ^
      text.hashCode ^
      html.hashCode ^
      blockedImages.hashCode ^
      hasAttachment.hashCode ^
      unread.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          threadId == other.threadId &&
          fromName == other.fromName &&
          fromAddr == other.fromAddr &&
          to == other.to &&
          date == other.date &&
          snippet == other.snippet &&
          text == other.text &&
          html == other.html &&
          blockedImages == other.blockedImages &&
          hasAttachment == other.hasAttachment &&
          unread == other.unread &&
          attachments == other.attachments;
}

/// Flat event record: `kind` is one of started, folder, finished, error.
class SyncEventDto {
  final String kind;
  final PlatformInt64 accountId;
  final String folder;
  final int fetched;
  final int removed;
  final String message;

  const SyncEventDto({
    required this.kind,
    required this.accountId,
    required this.folder,
    required this.fetched,
    required this.removed,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      accountId.hashCode ^
      folder.hashCode ^
      fetched.hashCode ^
      removed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          accountId == other.accountId &&
          folder == other.folder &&
          fetched == other.fetched &&
          removed == other.removed &&
          message == other.message;
}

class SyncSummaryDto {
  final int accounts;
  final int fetched;
  final int removed;
  final List<String> errors;

  const SyncSummaryDto({
    required this.accounts,
    required this.fetched,
    required this.removed,
    required this.errors,
  });

  @override
  int get hashCode =>
      accounts.hashCode ^ fetched.hashCode ^ removed.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSummaryDto &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          fetched == other.fetched &&
          removed == other.removed &&
          errors == other.errors;
}

class ThreadDto {
  final PlatformInt64 id;
  final PlatformInt64 accountId;
  final String subject;
  final List<String> participants;

  /// Unix seconds, UTC.
  final PlatformInt64 lastDate;
  final int msgCount;
  final int unreadCount;
  final String snippet;
  final bool hasAttachment;
  final bool starred;

  const ThreadDto({
    required this.id,
    required this.accountId,
    required this.subject,
    required this.participants,
    required this.lastDate,
    required this.msgCount,
    required this.unreadCount,
    required this.snippet,
    required this.hasAttachment,
    required this.starred,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      subject.hashCode ^
      participants.hashCode ^
      lastDate.hashCode ^
      msgCount.hashCode ^
      unreadCount.hashCode ^
      snippet.hashCode ^
      hasAttachment.hashCode ^
      starred.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          subject == other.subject &&
          participants == other.participants &&
          lastDate == other.lastDate &&
          msgCount == other.msgCount &&
          unreadCount == other.unreadCount &&
          snippet == other.snippet &&
          hasAttachment == other.hasAttachment &&
          starred == other.starred;
}
