// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_dto`, `attachment_to_dto`, `bin_role`, `core`, `draft_to_dto`, `dto_to_attachment`, `dto_to_draft`, `filed`, `fmt_addr`, `new`, `parse_addr`, `role_name`, `security`, `server`, `thread_dto`

/// Open (or create) the profile database under `data_dir`. Idempotent.
Future<void> openCore({required String dataDir}) =>
    RustLib.instance.api.crateApiMailOpenCore(dataDir: dataDir);

Future<List<AccountDto>> listAccounts() =>
    RustLib.instance.api.crateApiMailListAccounts();

/// Register an account; the password goes to the OS keychain. Fails when the address is
/// already added, so a second add cannot overwrite a working password.
Future<AccountDto> addImapAccount({
  required String email,
  required String displayName,
  required ServerDto imap,
  required ServerDto smtp,
  required bool localBridge,
  required String password,
}) => RustLib.instance.api.crateApiMailAddImapAccount(
  email: email,
  displayName: displayName,
  imap: imap,
  smtp: smtp,
  localBridge: localBridge,
  password: password,
);

/// Sign in to IMAP once; nothing is stored. The error text carries the server's reason;
/// pass it to [diagnose_error] for something to show.
Future<void> testImapLogin({
  required String email,
  required ServerDto imap,
  required bool localBridge,
  required String password,
}) => RustLib.instance.api.crateApiMailTestImapLogin(
  email: email,
  imap: imap,
  localBridge: localBridge,
  password: password,
);

/// Sign in to SMTP once without sending anything.
Future<void> testSmtpLogin({
  required String email,
  required ServerDto smtp,
  required bool localBridge,
  required String password,
}) => RustLib.instance.api.crateApiMailTestSmtpLogin(
  email: email,
  smtp: smtp,
  localBridge: localBridge,
  password: password,
);

/// The SMTP server usually paired with an IMAP host (`imap.x` → `smtp.x`).
ServerDto? suggestSmtp({required String imapHost}) =>
    RustLib.instance.api.crateApiMailSuggestSmtp(imapHost: imapHost);

/// Turn an error from sign-in or sync into a title and a hint.
DiagnosisDto diagnoseError({required String message, required String host}) =>
    RustLib.instance.api.crateApiMailDiagnoseError(
      message: message,
      host: host,
    );

/// Replace the stored password of an account (after the server started refusing it).
Future<void> updateAccountPassword({
  required PlatformInt64 id,
  required String password,
}) => RustLib.instance.api.crateApiMailUpdateAccountPassword(
  id: id,
  password: password,
);

Future<void> removeAccount({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMailRemoveAccount(id: id);

/// Folders one can open or move mail into (`\\Noselect` containers such as `[Gmail]` left
/// out), with names decoded from IMAP's modified UTF-7 for display.
Future<List<FolderDto>> listFolders({required PlatformInt64 accountId}) =>
    RustLib.instance.api.crateApiMailListFolders(accountId: accountId);

Future<List<ThreadDto>> listThreads({
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiMailListThreads(query: query, limit: limit);

/// One thread by id, wherever it lives (snoozed, archived, any folder); None when gone.
Future<ThreadDto?> getThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailGetThread(threadId: threadId);

Future<List<MessageDto>> threadMessages({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailThreadMessages(threadId: threadId);

/// Sanitized HTML body of one message. With `load_images`, remote images stay in and inline
/// images missing from the cache are fetched from the server.
Future<String?> messageHtml({
  required PlatformInt64 messageId,
  required bool loadImages,
}) => RustLib.instance.api.crateApiMailMessageHtml(
  messageId: messageId,
  loadImages: loadImages,
);

/// Path of the attachment in the app's file cache (fetched from the server when needed).
/// This is the file to hand to "open with" or a share sheet.
Future<String> openAttachment({
  required PlatformInt64 messageId,
  required int idx,
}) => RustLib.instance.api.crateApiMailOpenAttachment(
  messageId: messageId,
  idx: idx,
);

/// Save an attachment into `dir` under a free name; returns the path written.
Future<String> saveAttachment({
  required PlatformInt64 messageId,
  required int idx,
  required String dir,
}) => RustLib.instance.api.crateApiMailSaveAttachment(
  messageId: messageId,
  idx: idx,
  dir: dir,
);

/// Describe a local file for a draft: name, size, MIME type from the extension.
/// The extension (lower case) of an attachment that could run code or open a browser when
/// opened, judged by the name it will be saved under; None for ordinary files.
String? riskyExtension({required String name}) =>
    RustLib.instance.api.crateApiMailRiskyExtension(name: name);

/// The name an attachment is saved under (invisible characters removed, device names
/// renamed): what the chip should show.
String safeFileName({required String name}) =>
    RustLib.instance.api.crateApiMailSafeFileName(name: name);

Future<DraftAttachmentDto> describeFile({required String path}) =>
    RustLib.instance.api.crateApiMailDescribeFile(path: path);

Future<int> unreadCount() => RustLib.instance.api.crateApiMailUnreadCount();

/// Out of the inbox; `moved` is 0 when it was not there.
Future<FiledDto> archiveThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailArchiveThread(threadId: threadId);

/// To Trash; `moved` is 0 when it was there already (or only in Sent elsewhere).
Future<FiledDto> trashThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailTrashThread(threadId: threadId);

/// The conversation's messages in Trash and Spam: what Delete forever asks about, and all
/// it deletes (empty: nothing of it is in Trash or Spam).
Future<List<BinCopyDto>> binCopies({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailBinCopies(threadId: threadId);

/// Delete forever the copies [bin_copies] named, those still in Trash or Spam: they leave
/// the server for good. Mail that joined the conversation since stays. Returns how many.
Future<int> deleteForever({required List<BinCopyDto> copies}) =>
    RustLib.instance.api.crateApiMailDeleteForever(copies: copies);

/// Read one account's Trash (`trash`) or Spam (`junk`) from the server again, its queued
/// changes first, and say what it holds. None when the account has no such folder. Fails
/// when the folder could not be read: nothing is emptied from what is not known.
Future<BinCheckDto?> syncBin({
  required PlatformInt64 accountId,
  required String role,
}) =>
    RustLib.instance.api.crateApiMailSyncBin(accountId: accountId, role: role);

/// Empty the Trash or Spam that [sync_bin] read: all of it leaves the server for good,
/// but for mail a queued restore takes out and mail that came into view after the check.
/// Refused when the check is more than 15 minutes old. Returns how many messages went from
/// this device.
Future<int> emptyFolder({required BinCheckDto check}) =>
    RustLib.instance.api.crateApiMailEmptyFolder(check: check);

/// The next 200 older messages of each folder the list `query` shows, on one account.
Future<OlderDto> loadOlder({
  required PlatformInt64 accountId,
  required String query,
}) => RustLib.instance.api.crateApiMailLoadOlder(
  accountId: accountId,
  query: query,
);

/// Look on one account's server for what `query` names; matches then show in `threads`.
Future<int> searchServer({
  required PlatformInt64 accountId,
  required String query,
}) => RustLib.instance.api.crateApiMailSearchServer(
  accountId: accountId,
  query: query,
);

/// Create the `archive` or `trash` folder the account's server is missing; returns its name.
Future<String> createRoleFolder({
  required PlatformInt64 accountId,
  required String role,
}) => RustLib.instance.api.crateApiMailCreateRoleFolder(
  accountId: accountId,
  role: role,
);

Future<void> markRead({required PlatformInt64 threadId, required bool read}) =>
    RustLib.instance.api.crateApiMailMarkRead(threadId: threadId, read: read);

Future<void> starThread({required PlatformInt64 threadId, required bool on_}) =>
    RustLib.instance.api.crateApiMailStarThread(threadId: threadId, on_: on_);

/// "Move to…" any folder of the thread's account; returns how many messages moved.
Future<int> moveThread({
  required PlatformInt64 threadId,
  required PlatformInt64 folderId,
}) => RustLib.instance.api.crateApiMailMoveThread(
  threadId: threadId,
  folderId: folderId,
);

/// Hide the thread from the inbox until `until` (Unix seconds).
Future<void> snoozeThread({
  required PlatformInt64 threadId,
  required PlatformInt64 until,
}) => RustLib.instance.api.crateApiMailSnoozeThread(
  threadId: threadId,
  until: until,
);

Future<void> unsnoozeThread({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailUnsnoozeThread(threadId: threadId);

/// Wake threads whose snooze ended; returns how many woke.
Future<int> wakeSnoozed() => RustLib.instance.api.crateApiMailWakeSnoozed();

/// When the next snooze ends (Unix seconds), to schedule a wake-up.
Future<PlatformInt64?> nextSnoozeWake() =>
    RustLib.instance.api.crateApiMailNextSnoozeWake();

Future<DraftDto> replyDraft({
  required PlatformInt64 threadId,
  required bool replyAll,
}) => RustLib.instance.api.crateApiMailReplyDraft(
  threadId: threadId,
  replyAll: replyAll,
);

Future<DraftDto> forwardDraft({required PlatformInt64 threadId}) =>
    RustLib.instance.api.crateApiMailForwardDraft(threadId: threadId);

/// Empty draft (signature included) from the given account, or the first one.
Future<DraftDto> newDraft({PlatformInt64? accountId}) =>
    RustLib.instance.api.crateApiMailNewDraft(accountId: accountId);

/// Name shown in From, and the signature new drafts start with.
Future<void> updateAccount({
  required PlatformInt64 id,
  required String displayName,
  required String signature,
}) => RustLib.instance.api.crateApiMailUpdateAccount(
  id: id,
  displayName: displayName,
  signature: signature,
);

Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiMailGetSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiMailSetSetting(key: key, value: value);

/// Save a draft (insert, or update `id` in place); returns its id.
Future<PlatformInt64> saveLocalDraft({
  PlatformInt64? id,
  required String kind,
  required DraftDto draft,
}) => RustLib.instance.api.crateApiMailSaveLocalDraft(
  id: id,
  kind: kind,
  draft: draft,
);

/// Every saved draft, most recently edited first.
Future<List<SavedDraftDto>> listLocalDrafts() =>
    RustLib.instance.api.crateApiMailListLocalDrafts();

Future<void> deleteLocalDraft({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiMailDeleteLocalDraft(id: id);

/// SMTP send; copies to Sent where the server does not; flags the original as answered.
/// Send over SMTP. An error means nothing went out; `Some(text)` means it went out but a
/// later step (the copy in Sent) failed.
Future<String?> sendDraft({required DraftDto draft}) =>
    RustLib.instance.api.crateApiMailSendDraft(draft: draft);

Future<SyncSummaryDto> syncAll({required bool inboxOnly}) =>
    RustLib.instance.api.crateApiMailSyncAll(inboxOnly: inboxOnly);

/// Sit in IMAP IDLE on the account's inbox. Returns true when the server reported a change,
/// false when `timeout_secs` passed quietly. Errors surface as exceptions (no connection, auth…).
Future<bool> waitForChange({
  required PlatformInt64 accountId,
  required int timeoutSecs,
}) => RustLib.instance.api.crateApiMailWaitForChange(
  accountId: accountId,
  timeoutSecs: timeoutSecs,
);

/// Sync one account (inbox only when `inbox_only`).
Future<SyncSummaryDto> syncAccount({
  required PlatformInt64 accountId,
  required bool inboxOnly,
}) => RustLib.instance.api.crateApiMailSyncAccount(
  accountId: accountId,
  inboxOnly: inboxOnly,
);

/// Subscribe to sync events. The stream stays open for the life of the app.
Stream<SyncEventDto> syncEvents() =>
    RustLib.instance.api.crateApiMailSyncEvents();

class AccountDto {
  final PlatformInt64 id;
  final String email;
  final String kind;
  final String displayName;
  final int unread;
  final String signature;
  final String imapHost;
  final int imapPort;

  /// `tls` or `starttls`.
  final String imapSecurity;

  /// Empty when the SMTP server is guessed from the IMAP one at send time.
  final String smtpHost;
  final int smtpPort;
  final String smtpSecurity;

  /// A bridge on this computer (Proton) whose self-signed certificate is accepted.
  final bool localBridge;

  /// `password` or `xoauth2` (signed in on the provider's page).
  final String auth;

  const AccountDto({
    required this.id,
    required this.email,
    required this.kind,
    required this.displayName,
    required this.unread,
    required this.signature,
    required this.imapHost,
    required this.imapPort,
    required this.imapSecurity,
    required this.smtpHost,
    required this.smtpPort,
    required this.smtpSecurity,
    required this.localBridge,
    required this.auth,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      email.hashCode ^
      kind.hashCode ^
      displayName.hashCode ^
      unread.hashCode ^
      signature.hashCode ^
      imapHost.hashCode ^
      imapPort.hashCode ^
      imapSecurity.hashCode ^
      smtpHost.hashCode ^
      smtpPort.hashCode ^
      smtpSecurity.hashCode ^
      localBridge.hashCode ^
      auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email &&
          kind == other.kind &&
          displayName == other.displayName &&
          unread == other.unread &&
          signature == other.signature &&
          imapHost == other.imapHost &&
          imapPort == other.imapPort &&
          imapSecurity == other.imapSecurity &&
          smtpHost == other.smtpHost &&
          smtpPort == other.smtpPort &&
          smtpSecurity == other.smtpSecurity &&
          localBridge == other.localBridge &&
          auth == other.auth;
}

class AttachmentDto {
  final PlatformInt64 messageId;
  final int idx;
  final String name;
  final String mime;
  final PlatformInt64 size;

  const AttachmentDto({
    required this.messageId,
    required this.idx,
    required this.name,
    required this.mime,
    required this.size,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      idx.hashCode ^
      name.hashCode ^
      mime.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          idx == other.idx &&
          name == other.name &&
          mime == other.mime &&
          size == other.size;
}

/// What a fresh read of Trash or Spam showed; [empty_folder] deletes exactly that.
class BinCheckDto {
  final PlatformInt64 folderId;
  final int uidvalidity;
  final int below;
  final Uint32List seen;

  /// When it was read (Unix seconds).
  final PlatformInt64 readAt;

  /// What went wrong on the way, such as a restore the server refused (its message is
  /// back in the folder): said in the question.
  final List<String> notes;

  const BinCheckDto({
    required this.folderId,
    required this.uidvalidity,
    required this.below,
    required this.seen,
    required this.readAt,
    required this.notes,
  });

  @override
  int get hashCode =>
      folderId.hashCode ^
      uidvalidity.hashCode ^
      below.hashCode ^
      seen.hashCode ^
      readAt.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BinCheckDto &&
          runtimeType == other.runtimeType &&
          folderId == other.folderId &&
          uidvalidity == other.uidvalidity &&
          below == other.below &&
          seen == other.seen &&
          readAt == other.readAt &&
          notes == other.notes;
}

/// One message in Trash or Spam, as the server knows it.
class BinCopyDto {
  final PlatformInt64 folderId;
  final int uidvalidity;
  final int uid;

  const BinCopyDto({
    required this.folderId,
    required this.uidvalidity,
    required this.uid,
  });

  @override
  int get hashCode => folderId.hashCode ^ uidvalidity.hashCode ^ uid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BinCopyDto &&
          runtimeType == other.runtimeType &&
          folderId == other.folderId &&
          uidvalidity == other.uidvalidity &&
          uid == other.uid;
}

/// What went wrong, for people: `kind` is auth, network, tls, server or local.
class DiagnosisDto {
  final String kind;
  final String title;
  final String? hint;

  const DiagnosisDto({required this.kind, required this.title, this.hint});

  @override
  int get hashCode => kind.hashCode ^ title.hashCode ^ hint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosisDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          title == other.title &&
          hint == other.hint;
}

/// A file going out with a draft: a local `path`, or part `idx` of stored message `message_id`.
class DraftAttachmentDto {
  final String name;
  final String mime;
  final PlatformInt64 size;
  final String? path;
  final PlatformInt64? messageId;
  final int? idx;

  const DraftAttachmentDto({
    required this.name,
    required this.mime,
    required this.size,
    this.path,
    this.messageId,
    this.idx,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      mime.hashCode ^
      size.hashCode ^
      path.hashCode ^
      messageId.hashCode ^
      idx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftAttachmentDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          mime == other.mime &&
          size == other.size &&
          path == other.path &&
          messageId == other.messageId &&
          idx == other.idx;
}

/// A message being written. Addresses are `Name <addr>` or bare `addr`.
class DraftDto {
  final PlatformInt64 accountId;
  final String from;
  final List<String> to;
  final List<String> cc;
  final List<String> bcc;
  final String subject;
  final String text;
  final String? inReplyTo;
  final List<String> references;
  final List<DraftAttachmentDto> attachments;

  const DraftDto({
    required this.accountId,
    required this.from,
    required this.to,
    required this.cc,
    required this.bcc,
    required this.subject,
    required this.text,
    this.inReplyTo,
    required this.references,
    required this.attachments,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      from.hashCode ^
      to.hashCode ^
      cc.hashCode ^
      bcc.hashCode ^
      subject.hashCode ^
      text.hashCode ^
      inReplyTo.hashCode ^
      references.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DraftDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          from == other.from &&
          to == other.to &&
          cc == other.cc &&
          bcc == other.bcc &&
          subject == other.subject &&
          text == other.text &&
          inReplyTo == other.inReplyTo &&
          references == other.references &&
          attachments == other.attachments;
}

class FiledDto {
  /// How many messages moved (0: not in the inbox, or already in Trash).
  final int moved;
  final MissingFolderDto? missing;

  const FiledDto({required this.moved, this.missing});

  @override
  int get hashCode => moved.hashCode ^ missing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FiledDto &&
          runtimeType == other.runtimeType &&
          moved == other.moved &&
          missing == other.missing;
}

class FolderDto {
  final PlatformInt64 id;
  final PlatformInt64 accountId;
  final String name;
  final String role;

  const FolderDto({
    required this.id,
    required this.accountId,
    required this.name,
    required this.role,
  });

  @override
  int get hashCode =>
      id.hashCode ^ accountId.hashCode ^ name.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          name == other.name &&
          role == other.role;
}

class MessageDto {
  final PlatformInt64 id;
  final PlatformInt64 threadId;
  final String fromName;
  final String fromAddr;
  final List<String> to;
  final PlatformInt64 date;
  final String snippet;

  /// Plain text body, derived from HTML when the message has no text part.
  final String? text;

  /// Sanitized HTML (no scripts, styles, forms; remote images blocked → `data-blocked-src`).
  final String? html;

  /// Remote images blocked plus inline images not available offline.
  final int blockedImages;

  /// The HTML sets its own text or background colours: made for a light page, shown on one.
  final bool styled;

  /// Sent from the account's own address (a reply then goes to its recipients).
  final bool isMine;
  final bool hasAttachment;
  final bool unread;

  /// Real attachments only; inline images render inside `html`.
  final List<AttachmentDto> attachments;

  const MessageDto({
    required this.id,
    required this.threadId,
    required this.fromName,
    required this.fromAddr,
    required this.to,
    required this.date,
    required this.snippet,
    this.text,
    this.html,
    required this.blockedImages,
    required this.styled,
    required this.isMine,
    required this.hasAttachment,
    required this.unread,
    required this.attachments,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      threadId.hashCode ^
      fromName.hashCode ^
      fromAddr.hashCode ^
      to.hashCode ^
      date.hashCode ^
      snippet.hashCode ^
      text.hashCode ^
      html.hashCode ^
      blockedImages.hashCode ^
      styled.hashCode ^
      isMine.hashCode ^
      hasAttachment.hashCode ^
      unread.hashCode ^
      attachments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          threadId == other.threadId &&
          fromName == other.fromName &&
          fromAddr == other.fromAddr &&
          to == other.to &&
          date == other.date &&
          snippet == other.snippet &&
          text == other.text &&
          html == other.html &&
          blockedImages == other.blockedImages &&
          styled == other.styled &&
          isMine == other.isMine &&
          hasAttachment == other.hasAttachment &&
          unread == other.unread &&
          attachments == other.attachments;
}

/// Archive or Delete had nowhere to put mail.
class MissingFolderDto {
  final PlatformInt64 accountId;

  /// `archive` or `trash`.
  final String role;

  /// Gmail hides the folder from IMAP: the switch is in Gmail's settings, not here.
  final bool gmail;
  final String message;

  const MissingFolderDto({
    required this.accountId,
    required this.role,
    required this.gmail,
    required this.message,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^ role.hashCode ^ gmail.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MissingFolderDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          role == other.role &&
          gmail == other.gmail &&
          message == other.message;
}

class OlderDto {
  final int fetched;

  /// The server has older mail still.
  final bool more;

  const OlderDto({required this.fetched, required this.more});

  @override
  int get hashCode => fetched.hashCode ^ more.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OlderDto &&
          runtimeType == other.runtimeType &&
          fetched == other.fetched &&
          more == other.more;
}

/// A draft kept on this device. `kind` is fresh, reply or forward.
class SavedDraftDto {
  final PlatformInt64 id;
  final String kind;
  final PlatformInt64 updatedAt;
  final DraftDto draft;

  const SavedDraftDto({
    required this.id,
    required this.kind,
    required this.updatedAt,
    required this.draft,
  });

  @override
  int get hashCode =>
      id.hashCode ^ kind.hashCode ^ updatedAt.hashCode ^ draft.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedDraftDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          updatedAt == other.updatedAt &&
          draft == other.draft;
}

/// One server as the add-account form describes it; `security` is `tls` or `starttls`.
class ServerDto {
  final String host;
  final int port;
  final String security;

  const ServerDto({
    required this.host,
    required this.port,
    required this.security,
  });

  @override
  int get hashCode => host.hashCode ^ port.hashCode ^ security.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerDto &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          security == other.security;
}

/// Flat event record: `kind` is one of started, folder, finished, error.
class SyncEventDto {
  final String kind;
  final PlatformInt64 accountId;
  final String folder;
  final int fetched;
  final int removed;
  final String message;

  const SyncEventDto({
    required this.kind,
    required this.accountId,
    required this.folder,
    required this.fetched,
    required this.removed,
    required this.message,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      accountId.hashCode ^
      folder.hashCode ^
      fetched.hashCode ^
      removed.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          accountId == other.accountId &&
          folder == other.folder &&
          fetched == other.fetched &&
          removed == other.removed &&
          message == other.message;
}

class SyncSummaryDto {
  final int accounts;
  final int fetched;
  final int removed;

  /// The account could not sync at all (sign-in, network).
  final List<String> errors;

  /// Folders that failed while the rest synced, as `folder: error`.
  final List<String> folderErrors;

  const SyncSummaryDto({
    required this.accounts,
    required this.fetched,
    required this.removed,
    required this.errors,
    required this.folderErrors,
  });

  @override
  int get hashCode =>
      accounts.hashCode ^
      fetched.hashCode ^
      removed.hashCode ^
      errors.hashCode ^
      folderErrors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSummaryDto &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          fetched == other.fetched &&
          removed == other.removed &&
          errors == other.errors &&
          folderErrors == other.folderErrors;
}

class ThreadDto {
  final PlatformInt64 id;
  final PlatformInt64 accountId;
  final String subject;
  final List<String> participants;

  /// Unix seconds, UTC.
  final PlatformInt64 lastDate;
  final int msgCount;
  final int unreadCount;
  final String snippet;
  final bool hasAttachment;
  final bool starred;

  /// Unix seconds: when a snooze ends (future) or ended (past).
  final PlatformInt64? snoozedUntil;

  const ThreadDto({
    required this.id,
    required this.accountId,
    required this.subject,
    required this.participants,
    required this.lastDate,
    required this.msgCount,
    required this.unreadCount,
    required this.snippet,
    required this.hasAttachment,
    required this.starred,
    this.snoozedUntil,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountId.hashCode ^
      subject.hashCode ^
      participants.hashCode ^
      lastDate.hashCode ^
      msgCount.hashCode ^
      unreadCount.hashCode ^
      snippet.hashCode ^
      hasAttachment.hashCode ^
      starred.hashCode ^
      snoozedUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountId == other.accountId &&
          subject == other.subject &&
          participants == other.participants &&
          lastDate == other.lastDate &&
          msgCount == other.msgCount &&
          unreadCount == other.unreadCount &&
          snippet == other.snippet &&
          hasAttachment == other.hasAttachment &&
          starred == other.starred &&
          snoozedUntil == other.snoozedUntil;
}
