// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mail.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `finish`, `mobile_redirect`, `put`, `take`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`

/// Which providers this build can sign in with (`google`, `microsoft`).
List<String> oauthProviders({required bool mobile}) =>
    RustLib.instance.api.crateApiSigninOauthProviders(mobile: mobile);

/// Start signing in with `provider` (`google`, `microsoft`). `mobile`: the phone flow with
/// the app's URL scheme; otherwise a loopback address on this computer. `expect_email`:
/// signing an existing account in again (also the hint for the provider's page).
Future<OAuthStartDto> oauthBegin({
  required String provider,
  required bool mobile,
  String? expectEmail,
}) => RustLib.instance.api.crateApiSigninOauthBegin(
  provider: provider,
  mobile: mobile,
  expectEmail: expectEmail,
);

/// Computers: wait for the browser to come back to the loopback address, then add the
/// account.
Future<AccountDto> oauthFinish({required String session}) =>
    RustLib.instance.api.crateApiSigninOauthFinish(session: session);

/// Phones: the URL the sign-in sheet came back with.
Future<AccountDto> oauthFinishWithRedirect({
  required String session,
  required String redirect,
}) => RustLib.instance.api.crateApiSigninOauthFinishWithRedirect(
  session: session,
  redirect: redirect,
);

Future<MobileAuthDto> oauthMobileRequest({required String provider}) =>
    RustLib.instance.api.crateApiSigninOauthMobileRequest(provider: provider);

/// Phones: the code and PKCE verifier the sign-in sheet came back with. `expect_email`:
/// signing an existing account in again.
Future<AccountDto> oauthComplete({
  required String provider,
  required String code,
  required String verifier,
  required String redirectUri,
  String? expectEmail,
}) => RustLib.instance.api.crateApiSigninOauthComplete(
  provider: provider,
  code: code,
  verifier: verifier,
  redirectUri: redirectUri,
  expectEmail: expectEmail,
);

/// Give up a sign-in that was started: a waiting [oauth_finish] returns `cancelled` and
/// the loopback listener closes.
void oauthCancel({required String session}) =>
    RustLib.instance.api.crateApiSigninOauthCancel(session: session);

/// What the phone's sign-in sheet (AppAuth) needs; the code it returns goes to
/// [oauth_complete], which trades it here.
class MobileAuthDto {
  final String clientId;
  final String redirectUri;
  final String authorizationEndpoint;
  final String tokenEndpoint;
  final List<String> scopes;

  /// Extra query parameters, as `key=value`.
  final List<String> parameters;

  const MobileAuthDto({
    required this.clientId,
    required this.redirectUri,
    required this.authorizationEndpoint,
    required this.tokenEndpoint,
    required this.scopes,
    required this.parameters,
  });

  @override
  int get hashCode =>
      clientId.hashCode ^
      redirectUri.hashCode ^
      authorizationEndpoint.hashCode ^
      tokenEndpoint.hashCode ^
      scopes.hashCode ^
      parameters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileAuthDto &&
          runtimeType == other.runtimeType &&
          clientId == other.clientId &&
          redirectUri == other.redirectUri &&
          authorizationEndpoint == other.authorizationEndpoint &&
          tokenEndpoint == other.tokenEndpoint &&
          scopes == other.scopes &&
          parameters == other.parameters;
}

class OAuthStartDto {
  /// Handed back to [oauth_finish] / [oauth_finish_with_redirect].
  final String session;

  /// Open this in the browser (or the system's sign-in sheet).
  final String url;

  /// The URL scheme the sheet should watch for (phones).
  final String callbackScheme;

  const OAuthStartDto({
    required this.session,
    required this.url,
    required this.callbackScheme,
  });

  @override
  int get hashCode => session.hashCode ^ url.hashCode ^ callbackScheme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OAuthStartDto &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          url == other.url &&
          callbackScheme == other.callbackScheme;
}
